export const SYSTEM_CONSTANTS = {
  APP_NAME: 'TILAWA API',
  API_VERSION: 'v1',
  DEFAULT_PAGE_SIZE: 20,
  MAX_PAGE_SIZE: 100,
  AUTH: {
    MAX_LOGIN_ATTEMPTS: 5,
    LOCKOUT_DURATION_MINUTES: 15,
    RESET_TOKEN_EXPIRY_MINUTES: 60,
  },
  HIFZ: {
    INITIAL_EASE_FACTOR: 250, // SM-2 ease factor (2.5 * 100)
    MIN_EASE_FACTOR: 130, // 1.3 * 100
  },
} as const
